# SLSA Provenance Generation Workflow for platform-samples
# Maintained by @CodexClub567
# This workflow is tailored for your sample projects repository.
# For more info, visit https://slsa.dev and https://github.com/slsa-framework/slsa-github-generator.

name: SLSA Provenance for platform-samples

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # Recommended: pin to a commit SHA for maximum security

      # ---- PERSONALIZED ARTIFACT BUILD STEP ----
      # Customize your build here. Add or change artifact names as needed.
      - name: Build sample artifacts for @CodexClub567
        run: |
          mkdir -p dist
          echo "artifact1 from platform-samples" > dist/artifact1
          echo "artifact2 from platform-samples" > dist/artifact2

      # ---- PROVENANCE SUBJECTS (HASHES) ----
      # Explicitly list your artifacts here.
      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail
          files="dist/artifact1 dist/artifact2"
          echo "hashes=$(sha256sum $files | base64 -w0)" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [build]
    permissions:
      actions: read   # For workflow path
      id-token: write # To sign provenance
      contents: write # To upload assets to release

    # Pin to a commit SHA if possible for maximum security.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true # Set to false if you want to skip uploading to the release

# Maintainer: @CodexClub567
# Need changes? Just ask Copilot Chat!
